plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme  

kramdown:
  parse_block_html: false

exclude: ['vendor', 'setup.sh', 'jekyll.sh']
include:
  - _pages

timezone: America/New_York


url: https://test-313.github.io 
baseurl: "/Fall19"  
github_url: https://github.com/test-313/Fall19

title: "CMU 17-313"
course: "17-313"
qtr: "F19"
quarter: "Fall 2019"

start_week: 1
start_date: 2019-08-25 
num_weeks: 16
extra_exam_week: true
sections: "10am,&nbsp;11am"

cal_dates: >
  [
    {"label":"F19 official start date", "date":"2019-08-26" },
    {"label":"F19 1st day of instruction", "date":"2019-08-27" },	
    {"label":"Univ Holiday", "date":"2019-09-11" },
    {"label":"Univ Holiday", "date":"2019-11-11" },
    {"label":"F19 instruction ends", "date":"2019-12-15" },
    {"label":"F19 finals start", "date":"2019-12-13" },
    {"label":"F19 finals end", "date":"2019-12-20" },
    {"label":"F19 qtr ends", "date":"2019-12-23" }
  ]


collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  project:
    output: true
    permalink: /project/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /staff/:path
  admin:
    output: true
    permalink: /admin/:path



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: project
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: staff
    values:
     layout: staff
  -
    scope:
     path: ""
     type: admin
    values:
     layout: default

  - scope:
     path: ""
     type: pages
    values:
     layout: default

head_scripts:
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
